version: '3'

services:
  lpz-db:
    image: postgres:15.2-alpine
    container_name: lpz-db
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_ADMIN}
      POSTGRES_PASSWORD: ${PG_ADMIN_PASS}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_ADMIN: ${PG_ADMIN}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data/:/var/lib/postgresql/data
    ports:
      - "$PORT:5432"
    networks:
      - ebay

networks:
  ebay:
    driver: bridge
    internal: false